#!/bin/bash
#SBATCH --job-name=CUDA_ENV
#SBATCH --output=CUDA_ENV.out
#SBATCH --cpus-per-task=1
#SBATCH --nodes=1
#SBATCH --nodelist=cn[19]
#SBATCH --time=07:30:00
#SBATCH --partition=scavenge
#SBATCH --mail-type=end,fail

module load CUDA/12.6.0
module load ollama/0.6.0-GCCcore-13.3.0-CUDA-12.6.0

CONDA=/home/jete/Miniconda3-py312_25.9.1-3-Linux-x86_64_MAIN

# Source conda so activate works in a batch script
source $CONDA/etc/profile.d/conda.sh

# Create env (skip if already exists)
$CONDA/bin/conda create -y -n rag_gpu python=3.12

# Now activate works
conda activate rag_gpu

# Install all packages
pip install \
    torch \
    sentence-transformers \
    faiss-gpu-cu12 \
    datasets \
    rank_bm25 \
    rouge-score \
    bert-score \
    transformers