"""
Build an NQ-format question set that is ANSWERABLE FROM A GIVEN ARTICLE SUBSET.

    python -m rag_pipeline.generate_subset_questions \
        data/wikiDump/articles_4000.jsonl \
        data/NQ/synthetic-subset-4000.csv

Why this exists: `data/NQ/Natural-Questions-Filtered.csv` is written against the
full KILT dump. Run it over a 4,000-article subset and almost every gold answer
is simply absent from the corpus, so recall is pinned near zero and nothing
downstream of retrieval is measuring anything. This script emits one question
per article of the subset, with a gold answer that is a verbatim span of that
article, so retrieval has a reachable target.

The questions are generated by high-precision surface patterns over the LEAD
PARAGRAPH only (never the rest of the article, where the subject of a sentence
is usually no longer the article's subject). Every emitted row is checked with
the same `has_answer` criterion the evaluator uses, against the article text —
a row that does not pass is dropped rather than shipped.

Output columns are exactly the three `loadDatasetNQ` reads —
question, long_answers, short_answers — plus wikipedia_id / wikipedia_title /
pattern, which pandas carries along and the loader ignores. They are there so a
result can be traced back to the article and the rule that produced it.
"""

import csv
import json
import re
import sys
from collections import Counter
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

# The relevance criterion is the evaluator's, not a lookalike: a row is only
# worth shipping if the metric that will judge it agrees the answer is present.
# metrics.py pulls in rouge_score/bert_score, which a plain interpreter outside
# the run environment does not have, hence the fallback — kept identical to
# metrics.has_answer, and the script says out loud which one it used.
try:
    from rag_pipeline.metrics import has_answer
    _CRITERION = "rag_pipeline.metrics.has_answer"
except Exception:
    _CRITERION = "inline copy of metrics.has_answer (metrics.py not importable)"

    def has_answer(passage_text: str, gold_answers: list[str]) -> bool:
        passage = re.sub(r"\s+", " ", passage_text.lower().strip())
        for answer in gold_answers:
            ans = re.sub(r"\s+", " ", answer.lower().strip())
            if not ans:
                continue
            prefix = r"\b" if ans[0].isalnum() else ""
            suffix = r"\b" if ans[-1].isalnum() else ""
            if re.search(f"{prefix}{re.escape(ans)}{suffix}", passage):
                return True
        return False


# =====================================================================
# Text utilities
# =====================================================================

MONTHS = ("January|February|March|April|May|June|July|August|September|"
          "October|November|December")

# A date as Wikipedia writes it: "1 April 1979", "July 30, 1946", "April 1979",
# or a bare year. Ordered longest-first so the fuller form wins.
DATE = (r"(?:\d{1,2} (?:" + MONTHS + r") \d{3,4}"
        r"|(?:" + MONTHS + r") \d{1,2}, \d{3,4}"
        r"|(?:" + MONTHS + r") \d{3,4}"
        r"|\d{3,4})")

# Kept out of the question text: an answer is only useful if the question does
# not already contain it, and a disambiguator like "(Bangladeshi TV channel)"
# reads as noise in a question.
PAREN = re.compile(r"\s*\([^()]*\)\s*$")


def mask_parens(text: str) -> str:
    """
    Same-length copy with parenthesised spans blanked out.

    Patterns are matched against the mask and then sliced out of the ORIGINAL
    string, so offsets stay valid and the answer is always a verbatim span. The
    masking is what stops "Percy Tyson Lewis (2 October 1884, Cape Town - 30
    January 1976, Durban) was a South African cricketer" from having its copula
    found inside the parenthetical, and stops a birth-date comma from being read
    as the end of a predicate.
    """
    out = list(text)
    depth = 0
    for i, ch in enumerate(text):
        if ch == "(":
            depth += 1
        if depth:
            out[i] = " "
        if ch == ")":
            depth = max(0, depth - 1)
    return "".join(out)


def sentences(paragraph: str):
    """(sentence, offset) pairs. Split on sentence-final punctuation followed by
    a capital; deliberately conservative, since a bad split only costs a
    candidate, never correctness (answers are re-verified against the article)."""
    spans = []
    start = 0
    for m in re.finditer(r"(?<=[.!?])\s+(?=[A-Z\"'(])", paragraph):
        spans.append((paragraph[start:m.start()], start))
        start = m.end()
    spans.append((paragraph[start:], start))
    return [(s, off) for s, off in spans if s.strip()]


TRAILING = {"of", "the", "a", "an", "in", "on", "at", "to", "by", "for", "with",
            "from", "as", "and", "or", "into", "near", "his", "her", "its",
            "their", "was", "is", "were", "are", "first", "also", "which",
            "that", "who", "over", "under", "during", "between"}


def clean_answer(span: str) -> str:
    """Trim an extracted span to something a grader can match: no dangling
    punctuation, no unbalanced bracket."""
    span = span.strip().strip(",;:")
    span = re.sub(r"\s+", " ", span)
    # "published by Marvel Comics. The character first appeared..." — a captured
    # span must not run into the next sentence. Only a stop after a real word
    # counts: the one in "Lester B. Pearson Award" is an initial, not an end.
    span = re.split(r"(?<=[a-z]{2})\.\s+", span)[0]
    if span.count("(") != span.count(")"):
        span = span.replace("(", "").replace(")", "")
    if span.count('"') % 2:
        span = span.replace('"', "")
    # A word-capped predicate tends to stop mid-phrase — "first performed in".
    # A gold answer ending on a dangling preposition costs exact-match and F1
    # against any sane generated answer, and drops nothing the grader needs.
    words = span.split()
    while words and words[-1].lower().strip(".,;:") in TRAILING:
        words.pop()
    span = " ".join(words)
    return span.strip().strip(".,;:").strip()


def q(text: str) -> str:
    """NQ question surface form: lowercase, no terminal question mark — the
    dataset this imitates is written that way, and the question string is handed
    to the retriever verbatim."""
    text = re.sub(r"\s+", " ", text).strip().rstrip("?")
    return text.lower()


# =====================================================================
# Patterns
# =====================================================================
# Each returns (pattern_name, question, answer, evidence_sentence) or None.
# `lead` is the lead paragraph, `masked` its parenthesis-blanked twin, `title`
# the article title with any disambiguator stripped.

AGENT_VERBS = {
    "written and directed": "wrote and directed",
    "written": "wrote", "directed": "directed", "created": "created",
    "produced": "produced", "composed": "composed", "designed": "designed",
    "founded": "founded", "developed": "developed", "published": "published",
    "painted": "painted", "invented": "invented", "discovered": "discovered",
    "built": "built", "hosted": "hosted", "edited": "edited",
    "translated": "translated", "recorded": "recorded", "performed": "performed",
}

EVENT_VERBS = {
    "released": "released", "published": "published", "founded": "founded",
    "established": "established", "formed": "formed", "opened": "opened",
    "launched": "launched", "built": "built", "introduced": "introduced",
    "created": "created", "adopted": "adopted", "completed": "completed",
    "discovered": "discovered", "incorporated": "incorporated",
    "inaugurated": "inaugurated", "dissolved": "dissolved",
    "disbanded": "disbanded", "constructed": "constructed",
    "enacted": "enacted", "signed": "signed", "abolished": "abolished",
    "renamed": "renamed", "demolished": "demolished",
}

PROPER = r"[A-Z][\w.'’-]*"
NAME = PROPER + r"(?:\s+(?:of|de|van|von|der|del|la|le)\s+" + PROPER + r"|\s+" + PROPER + r"){0,3}"

# An alias is a chain of capitalised tokens: matching tokens rather than "run to
# the next period" is what keeps "the Lester B. Pearson Award" from being cut
# down to "Lester B" at the initial's full stop.
ALIAS = (r"\"?[A-Z][\w'’&.-]*(?:\s+(?:of|the|and|for|de|la)\s+[A-Z][\w'’&.-]*"
         r"|\s+[A-Z][\w'’&.-]*){0,5}")


STOPWORDS = {"the", "a", "an", "of", "in", "on", "and", "for", "to", "at",
             "is", "was", "are", "were", "this", "it", "by", "de", "la"}


def content_words(text):
    return {w for w in re.findall(r"[a-z0-9]+", text.lower()) if w not in STOPWORDS}


def bare(title):
    """The title without a leading article, for matching against lead text."""
    return re.sub(r"^the\s+", "", title, flags=re.I)


def with_the(title):
    return title if title.lower().startswith("the ") else "the " + title


def first_sentence(lead):
    return sentences(lead)[0][0].strip()


def sentence_containing(lead, offset):
    hit = sentences(lead)[0][0]
    for sent, off in sentences(lead):
        if off <= offset < off + len(sent):
            hit = sent
    return hit.strip()


def subject_paren(lead, masked):
    """
    The lead up to its first copula — the span where a parenthetical still
    belongs to the article's subject.

    Without this, "Arrow in the Blue is the ... autobiography of Arthur Koestler
    (1905-1983)" yields "when did arrow in the blue die": a life span attached
    to someone mentioned in the predicate, read as the subject's own.
    """
    m = re.search(r"\b(?:is|was|are|were)\b", masked)
    return lead[:m.start()] if m else lead


def p_birth(lead, masked, title):
    # "(born 1 April 1979)" and "(2 October 1884, Cape Town - 30 January 1976)".
    head = subject_paren(lead, masked)
    m = re.search(r"\(\s*born\s+(?:on\s+)?(" + DATE + r")", head)
    if not m:
        m = re.search(r"\(\s*(?:[^()]*?,\s*)?(" + DATE + r")\s*[–—-]", head)
    if not m:
        return None
    ans = clean_answer(m.group(1))
    if not ans:
        return None
    return ("birth_date", q("when was " + title + " born"), ans, first_sentence(lead))


def p_death(lead, masked, title):
    # Only the death half of a "(birth - death)" span; a lone date is a birth.
    head = subject_paren(lead, masked)
    m = re.search(r"\(" + DATE + r"[^()]*?[–—-]\s*(?:[^()]*?,\s*)?(" + DATE + r")", head)
    if not m:
        return None
    ans = clean_answer(m.group(1))
    if not ans:
        return None
    return ("death_date", q("when did " + title + " die"), ans, first_sentence(lead))


def agent_name(span):
    """
    The name inside "by <span>", where the span may carry a nationality or a
    role in front of it: "by Hong Kong filmmaker Stanley Tong" is Stanley Tong,
    not Hong Kong. Capitalised runs are separated by lower-case words; a run
    after a plain lower-case word is the name the earlier run was describing, so
    the LAST run wins — except across "and", where the runs are co-authors and
    the first is the one the question is about.
    """
    tokens = span.split()
    runs, current, joined_by_and = [], [], False
    for tok in tokens:
        if re.match(r"[A-Z]", tok) or (current and tok in ("of", "de", "van",
                                                           "von", "der", "del")):
            current.append(tok)
            continue
        if current:
            runs.append(" ".join(current))
            current = []
        if tok.lower() == "and" and runs:
            joined_by_and = True
    if current:
        runs.append(" ".join(current))
    if not runs:
        return ""
    return runs[0] if joined_by_and else runs[-1]


def p_agent(lead, masked, title):
    verbs = "|".join(sorted(AGENT_VERBS, key=len, reverse=True))
    m = re.search(r"\b(" + verbs + r")\s+by\s+([^,.;:()]{2,60})", masked)
    if not m:
        return None
    ans = clean_answer(agent_name(lead[m.start(2):m.end(2)]))
    # One capitalised token is as likely to be a sentence-initial word or a
    # publisher abbreviation as it is a person; require a real name.
    if len(ans.split()) < 2:
        return None
    verb = AGENT_VERBS[m.group(1).lower()]
    return ("agent_" + verb.split()[0], q("who " + verb + " " + title), ans,
            sentence_containing(lead, m.start(2)))


def p_event_date(lead, masked, title):
    verbs = "|".join(sorted(EVENT_VERBS, key=len, reverse=True))
    m = re.search(r"\b(?:was|were)\s+(" + verbs + r")\s+(?:on|in)\s+(?:the\s+)?("
                  + DATE + r")", masked)
    if not m:
        return None
    ans = clean_answer(lead[m.start(2):m.end(2)])
    if not ans:
        return None
    verb = EVENT_VERBS[m.group(1).lower()]
    return ("event_" + verb, q("when was " + title + " " + verb), ans,
            sentence_containing(lead, m.start(2)))


def p_location(lead, masked, title):
    m = re.search(
        r"\b(?:is|was|are|were)\s+(?:a|an|the)\b[^.]{0,80}?"
        r"\b(?:located|situated|based|headquartered)\s+in\s+(?:the\s+)?"
        r"([A-Z][^.,;]{2,60})", masked)
    if not m:
        m = re.search(
            r"\b(?:is|was)\s+(?:a|an|the)\s+(?:[a-z-]+\s+){0,3}"
            r"(?:city|town|village|municipality|commune|hamlet|borough|county|"
            r"district|province|island|river|mountain|lake|park|stadium|"
            r"school|university|college|museum|church|cathedral|airport|"
            r"railway station|neighbourhood|neighborhood|suburb)\s+in\s+"
            r"(?:the\s+)?([A-Z][^.,;]{2,60})", masked)
    if not m:
        return None
    ans = clean_answer(lead[m.start(1):m.end(1)])
    if not ans or len(ans.split()) > 8:
        return None
    return ("location", q("where is " + title + " located"), ans,
            sentence_containing(lead, m.start(1)))


def p_population(lead, masked, title):
    m = re.search(r"population(?:\s+of|\s+was|\s+is)?\s+(?:about\s+|around\s+)?"
                  r"([\d][\d,.]{2,})", masked, re.I)
    if not m:
        return None
    ans = clean_answer(lead[m.start(1):m.end(1)])
    if not ans:
        return None
    return ("population", q("what is the population of " + title), ans,
            sentence_containing(lead, m.start(1)))


OCCURRENCE = {
    "took place": "when did {t} take place",
    "was fought": "when was {t} fought",
    "were fought": "when were {t} fought",
    "was held": "when was {t} held",
    "were held": "when were {t} held",
    "was signed": "when was {t} signed",
    "occurred": "when did {t} occur",
    "began": "when did {t} begin",
    "started": "when did {t} start",
    "ended": "when did {t} end",
    "aired": "when did {t} air",
    "premiered": "when did {t} premiere",
    "debuted": "when did {t} debut",
}

# Titles that name a dated event: "Battle of Vitoria (21 June 1813)" puts the
# date in the lead's first parenthetical with no verb at all, which is the one
# place the verb-driven date patterns cannot reach.
EVENT_TITLE = re.compile(
    r"^(?:the\s+)?(battle|siege|treaty|massacre|raid|revolt|uprising|rebellion|"
    r"earthquake|hurricane|invasion|coup|riots?|expedition|conference|congress|"
    r"summit|olympics|championship|election|referendum|festival|awards)\b",
    re.I)


def p_occurrence(lead, masked, title):
    verbs = "|".join(sorted(OCCURRENCE, key=len, reverse=True))
    m = re.search(r"\b(" + verbs + r")\s+(?:on|in)\s+(?:the\s+)?(" + DATE + r")", masked)
    if not m:
        return None
    ans = clean_answer(lead[m.start(2):m.end(2)])
    if not ans:
        return None
    stem = OCCURRENCE[m.group(1).lower()]
    return ("occurrence_" + m.group(1).split()[-1], q(stem.format(t=title)), ans,
            sentence_containing(lead, m.start(2)))


def p_event_title_date(lead, masked, title):
    if not EVENT_TITLE.match(title):
        return None
    # Only the first parenthetical, and only when it is a date and nothing else:
    # "(sometimes shown as "Vimiera")" must not be read as one.
    m = re.match(r"[^(]{0,120}\((" + DATE + r")\)", lead)
    if not m:
        return None
    ans = clean_answer(m.group(1))
    if not ans:
        return None
    return ("event_title_date", q("when did " + with_the(title) + " take place"), ans,
            first_sentence(lead))


def p_alias(lead, masked, title):
    """
    "The Academy Awards, also officially and popularly known as the Oscars, ..."

    A high-value pattern: the alias is distinctive, so a chunk only counts as
    relevant if it really is about this subject — unlike a bare year.
    """
    m = re.search(r"\b(?:(?:also|commonly|better|officially|popularly|"
                  r"colloquially|formerly|often|widely|simply|originally|"
                  r"locally|sometimes|generally)\s+)?(?:[a-z]+\s+){0,2}"
                  r"(known as|referred to as|called|nicknamed|abbreviated as)\s+"
                  r"(?:the\s+)?(" + ALIAS + r")", sentences(masked)[0][0])
    if not m:
        return None
    ans = clean_answer(lead[m.start(2):m.end(2)])
    if not ans or len(ans.split()) > 8:
        return None
    # An "alias" that repeats the title teaches the retriever nothing, and would
    # hand the answer to the generator inside the question.
    if ans.lower() in title.lower() or title.lower() in ans.lower():
        return None
    stem = ("what is " + title + " nicknamed" if m.group(1) == "nicknamed"
            else "what is " + title + " also known as")
    return ("alias", q(stem), ans, sentence_containing(lead, m.start(2)))


AWARD_VERBS = {
    "recognizes": "what does {t} recognize",
    "recognises": "what does {t} recognise",
    "honors": "what does {t} honor",
    "honours": "what does {t} honour",
    "commemorates": "what does {t} commemorate",
    "celebrates": "what does {t} celebrate",
    "is awarded to": "who is {t} awarded to",
    "is presented to": "who is {t} presented to",
    "is given to": "who is {t} given to",
    "is awarded for": "what is {t} awarded for",
    "is given for": "what is {t} given for",
}


def p_award(lead, masked, title):
    verbs = "|".join(sorted(AWARD_VERBS, key=len, reverse=True))
    m = re.search(r"\b(" + verbs + r")\s+([^.;]{5,120})", masked)
    if not m:
        return None
    span = lead[m.start(2):m.end(2)]
    span = re.split(r"[,;:]|\bwho\b|\bwhich\b|\bthat\b|\.\s", span)[0]
    ans = clean_answer(" ".join(span.split()[:12]))
    if not ans or len(ans.split()) < 2:
        return None
    return ("award", q(AWARD_VERBS[m.group(1).lower()].format(t=title)), ans,
            sentence_containing(lead, m.start(2)))


SUPERLATIVE = (r"capital|largest city|second largest city|capital city|"
               r"highest mountain|longest river|largest island|"
               r"national anthem|official language|national bird")


def p_superlative(lead, masked, title):
    """
    "Austin is the capital of Texas in the United States." — asked the way NQ
    asks it ("what is the capital of texas"), with the article's subject as the
    answer rather than as the question.
    """
    m = re.match(r"\s*(?:The\s+)?(" + re.escape(bare(title)) + r")\b[^.]{0,40}?\s+is\s+the\s+("
                 + SUPERLATIVE + r")\s+(?:city\s+)?of\s+(?:the\s+)?([A-Z][^.,;]{2,40})",
                 masked)
    if not m:
        return None
    ans = clean_answer(lead[m.start(1):m.end(1)])
    # "the highest mountain of the Eastern Caucasus and the highest peak of
    # Chechnya" — one superlative per question.
    place = clean_answer(re.split(r"\s+and\s+|\s+in\s+", lead[m.start(3):m.end(3)])[0])
    if not ans or not place or len(place.split()) > 6:
        return None
    return ("superlative", q("what is the " + m.group(2) + " of " + place), ans,
            first_sentence(lead))


def p_definition(lead, masked, title, is_person):
    """
    The lead's defining clause: "<subject> is/was <predicate>."

    This is the fallback that gives nearly every article a question, so it is
    the one that most needs trimming — the predicate is cut at the first comma,
    relative pronoun or clause boundary and capped at 12 words, because a gold
    answer longer than that cannot survive `exact_match` and starts to straddle
    chunk boundaries.
    """
    sent, off = sentences(masked)[0]
    m = re.search(r"^(.{0,220}?)\b(is|was|are|were)\s+(.{5,})$", sent)
    if not m:
        return None
    subject = m.group(1)
    if len(subject.split()) > 20:
        return None
    # The lead does not always open on the article's subject — "This is a list
    # of cities and towns in Sierra Leone", "In the Battle of Vimeiro ... the
    # British under General Wellesley". Without this check the predicate of
    # whatever the sentence IS about gets shipped as the answer to a question
    # about the article. One shared content word is enough: the subject is
    # normally the title, a bolded variant of it, or a full name.
    if not (content_words(subject) & content_words(title)) and \
            not re.match(r"\s*(?:it|he|she|they)\b", subject, re.I):
        return None
    pred_start = off + m.start(3)
    pred = lead[pred_start:pred_start + 200]
    # " (" ends it too: the predicate is sliced out of the unmasked lead, so a
    # parenthetical aside — "(link will display the full calendar)" — would
    # otherwise ride along inside the gold answer.
    pred = re.split(r"[,;:(]|\bwho\b|\bwhich\b|\bthat\b|\bwhere\b|\band\b"
                    r"|\bbut\b|\bfor\b|\bwith\b|\.\s", pred)[0]
    pred = " ".join(pred.split()[:12])
    ans = clean_answer(pred)
    if len(ans.split()) < 2:
        return None
    past = m.group(2).lower() in ("was", "were")
    # "Burgess Hill railway station is on the Brighton Main Line" defines by
    # position, not by category: asked as "what is X" the gold answer reads as a
    # non-answer, asked as "where is X" it is exactly right.
    if re.match(r"(?:on|in|at|near|located|situated)\b", ans, re.I):
        return ("definition_where", q("where is " + title), ans, first_sentence(lead))
    if is_person:
        stem = "who was" if past else "who is"
    else:
        stem = "what was" if past else "what is"
    return ("definition", q(stem + " " + title), ans, first_sentence(lead))


# =====================================================================
# Selection
# =====================================================================
# Distinctiveness, not naturalness, drives the ranking, and it is measured
# rather than guessed: `Corpus.elsewhere` counts how many other articles contain
# the candidate answer. This matters because retrieval is scored by containment
# — a chunk counts as relevant if the gold answer appears in it. A gold answer
# of "2006" is present in 790 of these 4,000 articles, so almost any chunk
# satisfies it and recall@k is measuring nothing. "Kazuki Takahashi" is in one.

# More other articles than this and the question is kept only as a last resort.
AMBIGUOUS = 20

def tier(pattern, answer, elsewhere):
    """
    Lower is picked first. `elsewhere` is how many OTHER articles of the corpus
    contain this answer.

    0  a specific question whose answer appears in no other article: a chunk
       satisfies it only if it really is about this subject.
    1  a specific question whose answer is shared with a handful of others.
    2  the definitional fallback. Last not because it is wrong but because it is
       the least discriminating question in the set — its answer is the first
       predicate of the lead, which the title alone already retrieves — and it
       is the only pattern that fires for roughly half the corpus.
    3  an answer common enough that relevance judgements over it are close to
       meaningless. Taken only when an article offers nothing else, and the
       output column `answer_elsewhere` lets these be filtered out downstream.
    """
    if elsewhere > AMBIGUOUS:
        return 3
    if pattern.startswith("definition"):
        return 2
    return 0 if elsewhere == 0 else 1


def on_subject(evidence, title):
    """
    Is the sentence the answer came from still talking about the article?

    A lead paragraph drifts: the article "Narumi Yasuda" has a later sentence
    about a single "composed by Haruomi Hosono", which reads to a regex exactly
    like the article's own subject being composed by him. Requiring the evidence
    sentence to name the subject — by a content word of the title, or by a
    pronoun standing in for it — drops those without touching the ordinary case,
    where the sentence opens on the title itself.
    """
    if content_words(evidence) & content_words(title):
        return True
    # A bare "the" is not enough — "The Academy of Motion Picture Arts and
    # Sciences was founded in 1927" is a different subject inside the Academy
    # Awards article. "The film", "the album", "the station" are anaphora for
    # the article itself, so those are.
    return bool(re.match(
        r"\s*(?:it|he|she|they|its|his|her|their)\b|"
        r"\s*the\s+(?:film|movie|album|song|single|book|novel|series|show|"
        r"station|team|club|city|town|village|building|church|band|game|"
        r"company|park|bridge|battle|award|tower|school|university|magazine|"
        r"newspaper|project|aircraft|ship|museum|river|mountain|island|"
        r"stadium|festival|episode|character|species|genus|law|act|treaty)\b",
        evidence, re.I))


class Corpus:
    """
    The subset, plus a token -> articles index used to count how widely an
    answer is repeated across it.

    The whole subset is held in memory; at 4,000 articles that is ~30 MB of text
    and a few hundred thousand posting lists. This is a dataset-preparation
    script run once per subset, not part of a measured phase — but a subset
    large enough to matter (hundreds of thousands of articles) would want a
    disk-backed index instead.
    """

    def __init__(self, articles):
        self.articles = articles
        self.index = {}
        for i, a in enumerate(articles):
            for tok in set(re.findall(r"[a-z0-9]+", a["text"].lower())):
                self.index.setdefault(tok, []).append(i)

    def elsewhere(self, answer, own):
        """
        How many articles other than `own` contain `answer`, counted by the
        evaluator's own criterion and capped: past the cap the exact number
        changes no decision, and the rarest-token posting list for something
        like "2006" is most of the corpus.
        """
        toks = re.findall(r"[a-z0-9]+", answer.lower())
        if not toks:
            return 0
        rarest = min(toks, key=lambda t: len(self.index.get(t, ())))
        hits = 0
        for i in self.index.get(rarest, ()):
            if i == own:
                continue
            if has_answer(self.articles[i]["text"], [answer]):
                hits += 1
                if hits > AMBIGUOUS * 5:
                    break
        return hits


def build(article, index, corpus=None, own=None):
    title = PAREN.sub("", article["wikipedia_title"]).strip()
    text = article["text"]
    lead = text.split("\n")[0].strip()
    # A list article has no subject of its own: "when did list of phil of the
    # future episodes premiere" is a question about the series, asked of its
    # episode table.
    if title.lower().startswith(("list of", "lists of", "index of",
                                 "timeline of", "outline of", "glossary of")) \
            or re.match(r"(?:This is )?an? (?:list|index|timeline) of", lead, re.I):
        return None, "list article"
    # "252 is a leap year starting on Thursday" — an article titled with a bare
    # year or a calendar day is an almanac entry, and "what was 252" is not a
    # question anyone asks.
    if re.fullmatch(r"\d{1,4}(?: BC)?", title) or \
            re.fullmatch(r"(?:" + MONTHS + r") \d{1,2}", title):
        return None, "calendar article"
    if not lead or len(lead.split()) < 12:
        return None, "lead too short"
    # "X may refer to:" / "X primarily refers to:" — a disambiguation stub has no
    # subject to ask about.
    if re.search(r"\b(may|primarily|can|also|usually) refers? to\s*:?\s*$", lead) \
            or lead.rstrip().endswith("refer to:"):
        return None, "disambiguation page"

    # "The Academy Awards, ... are awards for" reads as "what are THE academy
    # awards"; the bare title does not. Follow the lead's own usage.
    if re.match(r"The\s+" + re.escape(bare(title)) + r"\b", lead) \
            and not title.lower().startswith("the "):
        title = "the " + title

    masked = mask_parens(lead)
    # A person is a subject carrying its own dates: "(born 14 July 1966)",
    # "(1913 - 1978)". Those dates have to sit BEFORE the copula, or every
    # article whose lead merely mentions a dated person in its predicate —
    # "the autobiography of Arthur Koestler (1905-1983)" — reads as one.
    is_person = bool(re.search(r"\(\s*(?:born\s+)?" + DATE,
                               subject_paren(lead, masked))) and \
        bool(re.search(r"\b(?:was|is)\s+(?:a|an|the)\b", masked))

    candidates = []
    sweep = [p_agent, p_alias, p_location, p_award, p_superlative,
             p_occurrence, p_event_date, p_event_title_date, p_population]
    if is_person:
        # "when was X born" is a question about a person. A dated parenthetical
        # on a product or a band — "(1964-2020)" — reads identically to a
        # regex, so the person test gates these two patterns rather than living
        # inside them.
        sweep += [p_birth, p_death]
    for fn in sweep:
        c = fn(lead, masked, title)
        if c:
            candidates.append(c)
    c = p_definition(lead, masked, title, is_person)
    if c:
        candidates.append(c)

    # Every answer must be judgeable against the article by the evaluator's own
    # criterion, must not be handed to the model inside the question, and must
    # come from a sentence that is still about the article's subject.
    valid = [c for c in candidates
             if c[2] and has_answer(text, [c[2]])
             and c[2].lower() not in c[1].lower()
             # Population sentences are exempt: they are written as "The
             # population was 4,760 at the 2010 census", with the place named
             # only in the title, so the drift guard rejects nearly all of them
             # while the figure is in fact the article's own.
             and (c[0] == "population" or on_subject(c[3], title))]
    if not valid:
        return None, "no verifiable candidate"

    # Scored candidates: (tier, pattern, question, answer, evidence, elsewhere).
    scored = []
    for pattern, question, answer, evidence in valid:
        n_else = corpus.elsewhere(answer, own) if corpus else 0
        scored.append((tier(pattern, answer, n_else), pattern, question,
                       answer, evidence, n_else))

    best = min(s[0] for s in scored)
    pool = [s for s in scored if s[0] == best]
    # Rotate within the tier so the set is not 3,000 "when was X born": the
    # rotation is by article index, so it is deterministic and re-runnable.
    return pool[index % len(pool)], None


def main():
    source = sys.argv[1] if len(sys.argv) > 1 else "data/wikiDump/articles_4000.jsonl"
    output = sys.argv[2] if len(sys.argv) > 2 else "data/NQ/synthetic-subset-4000.csv"
    source = Path(source) if Path(source).is_absolute() else REPO_ROOT / source
    output = Path(output) if Path(output).is_absolute() else REPO_ROOT / output
    output.parent.mkdir(parents=True, exist_ok=True)

    print("source    : " + str(source))
    print("output    : " + str(output))
    print("criterion : " + _CRITERION)

    with open(source, encoding="utf-8") as fh:
        articles = [json.loads(line) for line in fh]
    print("articles  : %d" % len(articles))
    corpus = Corpus(articles)

    rows, skipped, seen = [], Counter(), set()
    for i, article in enumerate(articles):
        picked, reason = build(article, i, corpus, i)
        if not picked:
            skipped[reason] += 1
            continue
        _, pattern, question, answer, evidence, n_else = picked
        if question in seen:
            skipped["duplicate question"] += 1
            continue
        seen.add(question)
        rows.append({
            "question": question,
            "long_answers": evidence,
            "short_answers": answer,
            "wikipedia_id": article["wikipedia_id"],
            "wikipedia_title": article["wikipedia_title"],
            "pattern": pattern,
            # How many OTHER articles in the subset contain this gold answer,
            # counted with the evaluator's criterion and capped at 101. 0 means
            # a relevance judgement over it can only be satisfied by the right
            # article. Filter on it for a strict evaluation set.
            "answer_elsewhere": n_else,
        })
    n = len(articles)

    with open(output, "w", encoding="utf-8", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)

    print("\n%d questions from %d articles (%.1f%% coverage)"
          % (len(rows), n, 100.0 * len(rows) / n))
    for reason, count in skipped.most_common():
        print("  skipped %5d  %s" % (count, reason))
    print("\n  by pattern:")
    for pattern, count in Counter(r["pattern"] for r in rows).most_common():
        print("    %5d  %s" % (count, pattern))

    # The headline number for whether these questions can be scored: a gold
    # answer shared with many other articles makes irrelevant chunks count as
    # relevant, so retrieval metrics over those rows read high for free.
    unique = sum(1 for r in rows if r["answer_elsewhere"] == 0)
    few = sum(1 for r in rows if 0 < r["answer_elsewhere"] <= AMBIGUOUS)
    print("\n  answer distinctiveness (other articles containing the gold answer):")
    print("    %5d  none          — strict set" % unique)
    print("    %5d  1-%d" % (few, AMBIGUOUS))
    print("    %5d  more than %d  — kept, but filter with answer_elsewhere"
          % (len(rows) - unique - few, AMBIGUOUS))


if __name__ == "__main__":
    main()
